name: wasteagram
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  cloud_firestore: ^0.13.7
  cupertino_icons: ^0.1.3
  firebase_storage: ^3.1.6
  flutter:
    sdk: flutter
  image_picker: ^0.6.7
  intl: ^0.16.1
  location: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
